mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_ # 全局逻辑删除字段值
  # 原生配置
  configuration:
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启Mybatis二级缓存，默认为 true。
    cache-enabled: true
  # 实体枚举扫描
  type-enums-package: com.lemon.app.*.enums
  mapper-locations: classpath:/mapper/**.xml

zh:
  http:
    cors:
      enable: true
      access-control-allow-origin: "*"
      access-control-allow-methods: POST, PUT, GET, OPTIONS, DELETE
      access-control-allow-headers: Authorization, Content-Type
      access-control-max-age: 3600
    accept-language:
      # 请求国际化是否通过请求参数指定
      # request-param-lang：通过参数指定 - .../api?lang=zh_CN
      # header-accept-language: 通过头指定 - Accept-Language=zh_CN
      type: header-accept-language
  db:
    sequence:
      # 分布式ID的服务节点，如果不设置则根据服务器IP自动计算节点
      # 要么所有服务器都不设置，要指定就全部指定但不能重复
      # 范围：0-1023之间
      node-id: 1
  shiro:
    # session 超时时间，单位为秒
    session-timeout: 3600
    # session 刷新策略：实时刷新(Runtime); 临近刷新(Near)
    session-refresh-policy: Near
    # session临近多少秒内才刷新，session-refresh-policy=Near有效
    session-refresh-near: 600
    # session最长存活时间(秒)，>0有效
    session-max-live-time: 86400
    # rememberMe cookie有效时长（秒），默认一天
    cookie-timeout: 86400
    # 免认证的路径配置，如静态资源等，逗号分隔
    anon-url: /auth/login,/auth/index,/auth/403,/auth/401,/index/index,/actuator/**,/test/**,/sys/monitor/**
    # 认证失败跳转的url
    login-url: /auth/401
    # 登录成功后的url
    success-url: /auth/index
    # 登出后跳转的url
    logout-url:  /auth/index
    # 未授权跳转的url
    unauthorized-url: /auth/403

jasypt:
  encryptor:
    # 必须有此配置
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    # 生产环境要去掉，将其放入运行参数中 -Djasypt.encryptor.password=你的盐
    #password: salt

spring:
  web:
    locale: zh_CN
  profiles:
    active: boot
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  datasource:
    url: "ENC(9EBchHExdurIkG3qj95OcjzlcqTfjl6V40ygUZwL3A4ITKSfWWSFMQExgd/sVivYZg8GuOtBBBBggV7EpYhViRkdYRw3ZuYoas3yrzOBl/cPAQDsUzh1RgS4+DaJnE6PiQq5LMd7dxfGzfkbuuDU8brgXYNeX9UecoljFomtbSeW2jAuGyT4T6Zirj2RlxZT7FbjgQ5S/t+AJHCCGl+h3Z4aBTp1oHurEMeqoVibOIwONP1bdbnMKnH/Rx8in6klQJWCHvC51qxKmm8m2SQfoA==)"
    driver-class-name: com.mysql.jdbc.Driver
    username: "ENC(2YPT4O9fdwNk+2kwWrzOs10hIFAb4Ok1f2Bb3oqe4AmnZT3HnOcRHuhB91LBvAKA)"
    password: "ENC(q400Fvd/996XBHSGoZneYOF89p7nCZChLNBojpwmG97B/Nt9JZlAN2kJ1aw9gtet)"
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      auto-commit: false
  aop:
    proxy-target-class: true

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.lemon:  DEBUG

debug: true
